/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dj2.core;

import org.junit.Test;

import dj2.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        
    }
}
